#!/usr/bin/env python3
# Generate nextpnr-xilinx/xilinx/usp_bufce_leaf.inc from prjuray-db.
#
# In RCLK_INT_L/R a clock reaches the fabric through a BUFCE_LEAF, and prjuray
# spells that as a site feature keyed by the site's position in the tile:
#   RCLK_INT_L.BUFCE_LEAF_X0Y2.BUFCE_LEAF.IN_USE.V1
# nextpnr sees only the route-thru pip CLK_LEAF_SITES_3_CLK_LEAF <-
# CLK_LEAF_SITES_3_CLK_IN, and its chipdb carries NO site for such a pip --
# pip.site and the wire's site are both -1 and the wires have no bel pins, so
# the site cannot be recovered at runtime. The wire number is not the site
# number either: X0Y2 is CLK_LEAF_SITES_3 and X0Y1 is CLK_LEAF_SITES_14.
# Hence a generated table.
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
D = os.environ.get('URAY_DB', os.path.join(ROOT, 'prjuray-db', 'zynqusp'))
OUT = os.path.join(ROOT, 'nextpnr-xilinx', 'xilinx', 'usp_bufce_leaf.inc')

rows = []
for tt in ('RCLK_INT_L', 'RCLK_INT_R'):
    p = os.path.join(D, 'tile_types', 'tile_type_%s.json' % tt)
    if not os.path.exists(p):
        sys.exit('missing %s' % p)
    d = json.load(open(p))
    for s in d.get('sites', []):
        if s.get('prefix') != 'BUFCE_LEAF':
            continue
        w = s['site_pins'].get('CLK_IN', {}).get('wire')
        if w:
            rows.append((tt, w, 'BUFCE_LEAF_X%dY%d' % (s['x_coord'], s['y_coord'])))

with open(OUT, 'w') as f:
    f.write('// Generated by tools/gen_usp_bufce_leaf.py -- do not edit.\n')
    f.write('// CLK_LEAF_SITES_<n>_CLK_IN -> BUFCE_LEAF_X<x>Y<y>, from prjuray-db tile types.\n')
    f.write('// USP_BUFCE_LEAF(tile_type, clk_in_wire, site_name)\n')
    for r in rows:
        f.write('USP_BUFCE_LEAF("%s", "%s", "%s")\n' % r)
print('wrote %d entries to %s' % (len(rows), OUT))
