#!/usr/bin/env python3
# Generate nextpnr-xilinx/xilinx/usp_hdio_optff.inc from prjuray-db.
#
# An HDIO output pin is driven through the HDIOLOGIC site's optional output
# flip-flop, and prjuray models the combinational path through it as TWO
# features, not one:
#
#   HDIO_TOP_RIGHT.PIP.HDIO_LOGICPAIR_35_OPFFM_Q.HDIO_LOGICPAIR_35_OPFFM_D1  00_830
#   HDIO_TOP_RIGHT.HDIOLOGIC_M_X0Y3.OQ_MUX.NOT_OPTFF                        !00_826 01_825
#
# The pip bit says the route passes through the site; the site's output mux
# says what drives the pad. nextpnr sees only the pip, and -- exactly as for
# BUFCE_LEAF, see gen_usp_bufce_leaf.py -- its chipdb carries no site for it:
# pip.site, both wires' site and the wires' bel pins are all -1/absent, so the
# site cannot be recovered at runtime. Hence a generated table.
#
# The wire number is not the site number: HDIO_LOGICPAIR_14 is HDIOLOGIC_M_X0Y0
# and HDIO_LOGICPAIR_15 is HDIOLOGIC_S_X0Y0. Keyed on the Q (destination) wire
# because one site spells its D1 wire HDIO_LOGICPAIR_49_OPFFM_D1_PIN.
import glob, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
D = os.environ.get('URAY_DB', os.path.join(ROOT, 'prjuray-db', 'zynqusp'))
OUT = os.path.join(ROOT, 'nextpnr-xilinx', 'xilinx', 'usp_hdio_optff.inc')

paths = sorted(glob.glob(os.path.join(D, 'tile_types', 'tile_type_HDIO*.json')))
if not paths:
    sys.exit('no HDIO tile types under %s' % D)

rows = []
for p in paths:
    tt = os.path.basename(p)[len('tile_type_'):-len('.json')]
    d = json.load(open(p))
    for s in d.get('sites', []):
        prefix = s.get('prefix', '')
        if not prefix.startswith('HDIOLOGIC_'):
            continue
        site = '%s_X%dY%d' % (prefix, s['x_coord'], s['y_coord'])
        for pin, info in s.get('site_pins', {}).items():
            if pin.endswith('_Q') and 'OPFF' in pin:
                w = info.get('wire')
                if w:
                    rows.append((tt, w, site))

with open(OUT, 'w') as f:
    f.write('// Generated by tools/gen_usp_hdio_optff.py -- do not edit.\n')
    f.write('// HDIO_LOGICPAIR_<n>_OPFF{M,S}_Q -> HDIOLOGIC_{M,S}_X<x>Y<y>,\n')
    f.write('// from prjuray-db tile types.\n')
    f.write('// USP_HDIO_OPTFF(tile_type, q_wire, site_name)\n')
    for r in sorted(rows):
        f.write('USP_HDIO_OPTFF("%s", "%s", "%s")\n' % r)
print('wrote %d entries to %s' % (len(rows), OUT))
